### ISSUE TITLE
how can i link multiple bitcode files?

### ISSUE THREAD

**Issue by gibait** [compor/llvm-ir-cmake-utils#38]
i have created a LLVM IR target using `llvmir_attach_library` and a second target created with `llvmir_attach_opt_pass_target`. How can i link both bitcode files into one?

Thank you

**Comment by compor** [comment]
Hello there,

You haven't provided many details, but there are 2 ways:

1) you can either link the two binary files in cmake to produce a library or executable as usual and then attach the bitcode generation on that target using `llvm_ir_attach_library` etc.

2) use `llvm_ir_attach_link_target` using the the two targets you have created using `llvm_ir_attach_library` and `llvm_ir_atrach_opt_pass_target` as `DEPENDS` arguments.

You can find this in `example03` directory.
I'm assuming you need to go with 2) since you want specific optimizations on your second source file and not whatever -O flag from Clang you are using for the rest of the source files.

**Comment by gibait** [comment]
Hello! 

You are right, it was so obvious. I solved it using the latter method as you said, but this time I had to specify the relative path of one of the two LLVM IR target instead, unlike other before.

`llvmir_attach_link_target(TARGET ${source}_linked DEPENDS ${source}_bc llvm-ir/encode_bc/Encode.c.bc)` 

where `source` is the `llvm_ir_attach_library` target.

Thanks again. Closing.
